blank_issues_enabled: true
contact_links:
  - name: Community discussions
    url: https://github.com/elfchess-GHub/Hot2Trot/discussions
    about: Use this for open player discussion if GitHub Discussions is enabled for the repository.
